# Generated by Django 4.2.5 on 2023-09-04 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя/Псевданим')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.CharField(max_length=2000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('english_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Англиское название')),
                ('image', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Обложка')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер тома или сезона')),
                ('viewing_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации записи')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категория')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('genre', models.ManyToManyField(blank=True, to='blog.genre', verbose_name='Жанры')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.series', verbose_name='Серия')),
            ],
            options={
                'ordering': ['-viewing_date'],
            },
        ),
    ]
