# Generated by Django 4.2.5 on 2023-09-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_alternativename_artwork_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ManyToManyField(to='blog.categoryartwork', verbose_name='Категория'),
        ),
    ]
